nelmio_api_doc:
    resource: "@NelmioApiDocBundle/config/routing/swaggerui.php"
    prefix: /api/v1/docs

nelmio_api_doc_json:
    path: /api/v1/docs.json
    controller: nelmio_api_doc.controller.swagger_json
